# Generated by Django 3.1 on 2020-08-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField()),
                ('task_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='update_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.task')),
                ('update_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.update_types')),
            ],
        ),
    ]
