# Generated by Django 3.1 on 2020-08-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracker',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
